name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install pnpm
                uses: pnpm/action-setup@v4
                with:
                    version: 10

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: pnpm
            
            -   name: Install dependencies
                run: pnpm install
            
            -   name: Run ESLint
                run: pnpm run lint
            
            -   name: Run TypeScript checks
                run: pnpm run type-check
            
            -   name: Run Unit Tests
                run: pnpm run test:unit
            
            -   name: Build Library
                run: pnpm run build
                
            -   name: Upload artifact for GitHub Pages
                uses: actions/upload-pages-artifact@v3
                with:
                    path: 'dist'

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        concurrency:
            group: 'pages'
            cancel-in-progress: true
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
